-- MySQL Script generated by MySQL Workbench
-- Mon Oct 29 01:39:10 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producto` (
  `codigoProducto` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `precio` INT NULL,
  `stock` INT NULL,
  PRIMARY KEY (`codigoProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `codigoCliente` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `dirPost` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`codigoCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`compra` (
  `Producto_codigoProducto` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `fecha_compra` DATE NULL,
  PRIMARY KEY (`Producto_codigoProducto`, `Cliente_idCliente`),
  INDEX `fk_Producto_has_Cliente_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_Producto_has_Cliente_Producto_idx` (`Producto_codigoProducto` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_has_Cliente_Producto`
    FOREIGN KEY (`Producto_codigoProducto`)
    REFERENCES `mydb`.`Producto` (`codigoProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_has_Cliente_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proveedor` (
  `idProveedor` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `provincia` VARCHAR(45) NULL,
  PRIMARY KEY (`idProveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`suministra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`suministra` (
  `Producto_codigoProducto` INT NOT NULL,
  `Proveedor_idProveedor` INT NOT NULL,
  PRIMARY KEY (`Producto_codigoProducto`, `Proveedor_idProveedor`),
  INDEX `fk_Producto_has_Proveedor_Proveedor1_idx` (`Proveedor_idProveedor` ASC) VISIBLE,
  INDEX `fk_Producto_has_Proveedor_Producto1_idx` (`Producto_codigoProducto` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_has_Proveedor_Producto1`
    FOREIGN KEY (`Producto_codigoProducto`)
    REFERENCES `mydb`.`Producto` (`codigoProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_has_Proveedor_Proveedor1`
    FOREIGN KEY (`Proveedor_idProveedor`)
    REFERENCES `mydb`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `codigoCliente` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `dirPost` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`codigoCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo` (
  `idtipo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idtipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Anuncio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Anuncio` (
  `codigoAnuncio` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `tipo` INT NULL,
  `titulo` VARCHAR(45) NULL,
  `categoria` INT NULL,
  `precio` INT NULL,
  `tipo_idtipo` INT NOT NULL,
  `categoria_idcategoria` INT NOT NULL,
  PRIMARY KEY (`codigoAnuncio`),
  INDEX `fk_Anuncio_tipo1_idx` (`tipo_idtipo` ASC) VISIBLE,
  INDEX `fk_Anuncio_categoria1_idx` (`categoria_idcategoria` ASC) VISIBLE,
  CONSTRAINT `fk_Anuncio_tipo1`
    FOREIGN KEY (`tipo_idtipo`)
    REFERENCES `mydb`.`tipo` (`idtipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Anuncio_categoria1`
    FOREIGN KEY (`categoria_idcategoria`)
    REFERENCES `mydb`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contrata`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contrata` (
  `Cliente_codigoCliente` INT NOT NULL,
  `Anuncio_codigoAnuncio` INT NOT NULL,
  PRIMARY KEY (`Cliente_codigoCliente`, `Anuncio_codigoAnuncio`),
  INDEX `fk_Cliente_has_Anuncio_Anuncio1_idx` (`Anuncio_codigoAnuncio` ASC) VISIBLE,
  INDEX `fk_Cliente_has_Anuncio_Cliente1_idx` (`Cliente_codigoCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_has_Anuncio_Cliente1`
    FOREIGN KEY (`Cliente_codigoCliente`)
    REFERENCES `mydb`.`Cliente` (`codigoCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_has_Anuncio_Anuncio1`
    FOREIGN KEY (`Anuncio_codigoAnuncio`)
    REFERENCES `mydb`.`Anuncio` (`codigoAnuncio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Web`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Web` (
  `nombre` VARCHAR(100) NOT NULL,
  `URL` VARCHAR(45) NULL,
  `topico` VARCHAR(45) NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aparece`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aparece` (
  `Web_nombre` VARCHAR(100) NOT NULL,
  `Anuncio_codigoAnuncio` INT NOT NULL,
  `fechaIni` DATE NULL,
  `fechaFin` DATE NULL,
  PRIMARY KEY (`Web_nombre`, `Anuncio_codigoAnuncio`),
  INDEX `fk_Web_has_Anuncio_Anuncio1_idx` (`Anuncio_codigoAnuncio` ASC) VISIBLE,
  INDEX `fk_Web_has_Anuncio_Web1_idx` (`Web_nombre` ASC) VISIBLE,
  CONSTRAINT `fk_Web_has_Anuncio_Web1`
    FOREIGN KEY (`Web_nombre`)
    REFERENCES `mydb`.`Web` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Web_has_Anuncio_Anuncio1`
    FOREIGN KEY (`Anuncio_codigoAnuncio`)
    REFERENCES `mydb`.`Anuncio` (`codigoAnuncio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mueble`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mueble` (
  `nombre` VARCHAR(100) NOT NULL,
  `precio` INT NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pieza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pieza` (
  `idPieza` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idPieza`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`parte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`parte` (
  `Mueble_nombre` VARCHAR(100) NOT NULL,
  `Pieza_idPieza` INT NOT NULL,
  `cantidad` INT NULL,
  PRIMARY KEY (`Mueble_nombre`, `Pieza_idPieza`),
  INDEX `fk_Mueble_has_Pieza_Pieza1_idx` (`Pieza_idPieza` ASC) VISIBLE,
  INDEX `fk_Mueble_has_Pieza_Mueble1_idx` (`Mueble_nombre` ASC) VISIBLE,
  CONSTRAINT `fk_Mueble_has_Pieza_Mueble1`
    FOREIGN KEY (`Mueble_nombre`)
    REFERENCES `mydb`.`Mueble` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mueble_has_Pieza_Pieza1`
    FOREIGN KEY (`Pieza_idPieza`)
    REFERENCES `mydb`.`Pieza` (`idPieza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Almacen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Almacen` (
  `idAlmacen` INT NOT NULL,
  `pasillo` VARCHAR(45) NULL,
  `altura` INT NULL,
  PRIMARY KEY (`idAlmacen`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`almacenada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`almacenada` (
  `Almacen_idAlmacen` INT NOT NULL,
  `Pieza_idPieza` INT NOT NULL,
  `cantPieza` INT NULL,
  PRIMARY KEY (`Almacen_idAlmacen`, `Pieza_idPieza`),
  INDEX `fk_Almacen_has_Pieza_Pieza1_idx` (`Pieza_idPieza` ASC) VISIBLE,
  INDEX `fk_Almacen_has_Pieza_Almacen1_idx` (`Almacen_idAlmacen` ASC) VISIBLE,
  CONSTRAINT `fk_Almacen_has_Pieza_Almacen1`
    FOREIGN KEY (`Almacen_idAlmacen`)
    REFERENCES `mydb`.`Almacen` (`idAlmacen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Almacen_has_Pieza_Pieza1`
    FOREIGN KEY (`Pieza_idPieza`)
    REFERENCES `mydb`.`Pieza` (`idPieza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
